/**
 * Grade 3 ELA Skills - Common Core Aligned
 * 55 skills covering 273 school days (September 1 - May 31)
 */

import { Skill } from './types';

export const grade3ELASkills: Skill[] = [
  // ============================================================================
  // READING: LITERATURE (3.RL) - Days 1-35
  // ============================================================================

  {
    id: 'ask_answer_lit',
    name: 'Ask & Answer Questions (Literature)',
    description: 'Ask and answer questions referring explicitly to the text',
    domainCode: 'RL',
    ccssCode: '3.RL.1',
    ccssDescription: 'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.',
    schoolDayStart: 1,
    schoolDayEnd: 5,
    prerequisiteSkillId: null,
    sortOrder: 1,
  },
  {
    id: 'recount_stories',
    name: 'Recount Stories',
    description: 'Recount stories and determine central message, lesson, or moral',
    domainCode: 'RL',
    ccssCode: '3.RL.2',
    ccssDescription: 'Recount stories, including fables, folktales, and myths from diverse cultures; determine the central message, lesson, or moral and explain how it is conveyed through key details.',
    schoolDayStart: 6,
    schoolDayEnd: 10,
    prerequisiteSkillId: 'ask_answer_lit',
    sortOrder: 2,
  },
  {
    id: 'character_traits',
    name: 'Character Traits & Motivations',
    description: 'Describe characters and explain how their actions contribute to events',
    domainCode: 'RL',
    ccssCode: '3.RL.3',
    ccssDescription: 'Describe characters in a story (e.g., their traits, motivations, or feelings) and explain how their actions contribute to the sequence of events.',
    schoolDayStart: 11,
    schoolDayEnd: 15,
    prerequisiteSkillId: 'recount_stories',
    sortOrder: 3,
  },
  {
    id: 'literal_nonliteral',
    name: 'Literal & Nonliteral Language',
    description: 'Determine the meaning of literal and nonliteral language',
    domainCode: 'RL',
    ccssCode: '3.RL.4',
    ccssDescription: 'Determine the meaning of words and phrases as they are used in a text, distinguishing literal from nonliteral language.',
    schoolDayStart: 16,
    schoolDayEnd: 20,
    prerequisiteSkillId: 'character_traits',
    sortOrder: 4,
  },
  {
    id: 'story_structure',
    name: 'Story Structure',
    description: 'Refer to parts of stories, dramas, and poems using chapter, scene, stanza',
    domainCode: 'RL',
    ccssCode: '3.RL.5',
    ccssDescription: 'Refer to parts of stories, dramas, and poems when writing or speaking about a text, using terms such as chapter, scene, and stanza.',
    schoolDayStart: 21,
    schoolDayEnd: 25,
    prerequisiteSkillId: 'literal_nonliteral',
    sortOrder: 5,
  },
  {
    id: 'point_of_view_lit',
    name: 'Point of View (Literature)',
    description: 'Distinguish own point of view from narrator or characters',
    domainCode: 'RL',
    ccssCode: '3.RL.6',
    ccssDescription: 'Distinguish their own point of view from that of the narrator or those of the characters.',
    schoolDayStart: 26,
    schoolDayEnd: 30,
    prerequisiteSkillId: 'story_structure',
    sortOrder: 6,
  },
  {
    id: 'illustrations_text',
    name: 'Illustrations & Text',
    description: 'Explain how illustrations contribute to mood and meaning',
    domainCode: 'RL',
    ccssCode: '3.RL.7',
    ccssDescription: 'Explain how specific aspects of a text\'s illustrations contribute to what is conveyed by the words in a story (e.g., create mood, emphasize aspects of a character or setting).',
    schoolDayStart: 31,
    schoolDayEnd: 35,
    prerequisiteSkillId: 'point_of_view_lit',
    sortOrder: 7,
  },

  // ============================================================================
  // READING: INFORMATIONAL TEXT (3.RI) - Days 36-80
  // ============================================================================

  {
    id: 'ask_answer_info',
    name: 'Ask & Answer Questions (Informational)',
    description: 'Ask and answer questions about informational texts',
    domainCode: 'RI',
    ccssCode: '3.RI.1',
    ccssDescription: 'Ask and answer questions to demonstrate understanding of a text, referring explicitly to the text as the basis for the answers.',
    schoolDayStart: 36,
    schoolDayEnd: 40,
    prerequisiteSkillId: 'illustrations_text',
    sortOrder: 8,
  },
  {
    id: 'main_idea_details',
    name: 'Main Idea & Key Details',
    description: 'Determine the main idea and key details of a text',
    domainCode: 'RI',
    ccssCode: '3.RI.2',
    ccssDescription: 'Determine the main idea of a text; recount the key details and explain how they support the main idea.',
    schoolDayStart: 41,
    schoolDayEnd: 47,
    prerequisiteSkillId: 'ask_answer_info',
    sortOrder: 9,
  },
  {
    id: 'historical_scientific',
    name: 'Historical/Scientific Relationships',
    description: 'Describe relationships between events, ideas, or concepts',
    domainCode: 'RI',
    ccssCode: '3.RI.3',
    ccssDescription: 'Describe the relationship between a series of historical events, scientific ideas or concepts, or steps in technical procedures using language that pertains to time, sequence, and cause/effect.',
    schoolDayStart: 48,
    schoolDayEnd: 54,
    prerequisiteSkillId: 'main_idea_details',
    sortOrder: 10,
  },
  {
    id: 'academic_vocabulary',
    name: 'Academic Vocabulary',
    description: 'Determine meaning of academic and domain-specific words',
    domainCode: 'RI',
    ccssCode: '3.RI.4',
    ccssDescription: 'Determine the meaning of general academic and domain-specific words and phrases in a text relevant to a grade 3 topic or subject area.',
    schoolDayStart: 55,
    schoolDayEnd: 60,
    prerequisiteSkillId: 'historical_scientific',
    sortOrder: 11,
  },
  {
    id: 'text_features',
    name: 'Text Features',
    description: 'Use text features and search tools to locate information',
    domainCode: 'RI',
    ccssCode: '3.RI.5',
    ccssDescription: 'Use text features and search tools (e.g., key words, sidebars, hyperlinks) to locate information relevant to a given topic efficiently.',
    schoolDayStart: 61,
    schoolDayEnd: 66,
    prerequisiteSkillId: 'academic_vocabulary',
    sortOrder: 12,
  },
  {
    id: 'point_of_view_info',
    name: 'Point of View (Informational)',
    description: 'Distinguish own point of view from that of the author',
    domainCode: 'RI',
    ccssCode: '3.RI.6',
    ccssDescription: 'Distinguish their own point of view from that of the author of a text.',
    schoolDayStart: 67,
    schoolDayEnd: 72,
    prerequisiteSkillId: 'text_features',
    sortOrder: 13,
  },
  {
    id: 'visual_info',
    name: 'Visual Information',
    description: 'Use information from illustrations, maps, and photographs',
    domainCode: 'RI',
    ccssCode: '3.RI.7',
    ccssDescription: 'Use information gained from illustrations (e.g., maps, photographs) and the words in a text to demonstrate understanding of the text.',
    schoolDayStart: 73,
    schoolDayEnd: 78,
    prerequisiteSkillId: 'point_of_view_info',
    sortOrder: 14,
  },
  {
    id: 'logical_connections',
    name: 'Logical Connections',
    description: 'Describe connections between sentences and paragraphs',
    domainCode: 'RI',
    ccssCode: '3.RI.8',
    ccssDescription: 'Describe the logical connection between particular sentences and paragraphs in a text (e.g., comparison, cause/effect, first/second/third in a sequence).',
    schoolDayStart: 79,
    schoolDayEnd: 84,
    prerequisiteSkillId: 'visual_info',
    sortOrder: 15,
  },
  {
    id: 'compare_texts',
    name: 'Compare & Contrast Texts',
    description: 'Compare and contrast key points in two texts on the same topic',
    domainCode: 'RI',
    ccssCode: '3.RI.9',
    ccssDescription: 'Compare and contrast the most important points and key details presented in two texts on the same topic.',
    schoolDayStart: 85,
    schoolDayEnd: 90,
    prerequisiteSkillId: 'logical_connections',
    sortOrder: 16,
  },

  // ============================================================================
  // READING: FOUNDATIONAL SKILLS (3.RF) - Days 91-115
  // ============================================================================

  {
    id: 'phonics_decoding',
    name: 'Phonics & Word Recognition',
    description: 'Know and apply grade-level phonics in decoding words',
    domainCode: 'RF',
    ccssCode: '3.RF.3',
    ccssDescription: 'Know and apply grade-level phonics and word analysis skills in decoding words.',
    schoolDayStart: 91,
    schoolDayEnd: 98,
    prerequisiteSkillId: 'compare_texts',
    sortOrder: 17,
  },
  {
    id: 'prefixes_suffixes',
    name: 'Prefixes & Suffixes',
    description: 'Identify and understand meaning of common prefixes and suffixes',
    domainCode: 'RF',
    ccssCode: '3.RF.3a',
    ccssDescription: 'Identify and know the meaning of the most common prefixes and derivational suffixes.',
    schoolDayStart: 99,
    schoolDayEnd: 105,
    prerequisiteSkillId: 'phonics_decoding',
    sortOrder: 18,
  },
  {
    id: 'multisyllable_words',
    name: 'Multisyllable Words',
    description: 'Decode multisyllable words',
    domainCode: 'RF',
    ccssCode: '3.RF.3c',
    ccssDescription: 'Decode multisyllable words.',
    schoolDayStart: 106,
    schoolDayEnd: 112,
    prerequisiteSkillId: 'prefixes_suffixes',
    sortOrder: 19,
  },
  {
    id: 'fluency_accuracy',
    name: 'Reading Fluency',
    description: 'Read with sufficient accuracy and fluency to support comprehension',
    domainCode: 'RF',
    ccssCode: '3.RF.4',
    ccssDescription: 'Read with sufficient accuracy and fluency to support comprehension.',
    schoolDayStart: 113,
    schoolDayEnd: 120,
    prerequisiteSkillId: 'multisyllable_words',
    sortOrder: 20,
  },

  // ============================================================================
  // WRITING (3.W) - Days 121-170
  // ============================================================================

  {
    id: 'opinion_intro',
    name: 'Opinion Writing: Introduction',
    description: 'Introduce the topic and state an opinion',
    domainCode: 'W',
    ccssCode: '3.W.1a',
    ccssDescription: 'Introduce the topic or text they are writing about, state an opinion, and create an organizational structure.',
    schoolDayStart: 121,
    schoolDayEnd: 127,
    prerequisiteSkillId: 'fluency_accuracy',
    sortOrder: 21,
  },
  {
    id: 'opinion_reasons',
    name: 'Opinion Writing: Reasons',
    description: 'Provide reasons that support the opinion',
    domainCode: 'W',
    ccssCode: '3.W.1b',
    ccssDescription: 'Provide reasons that support the opinion.',
    schoolDayStart: 128,
    schoolDayEnd: 134,
    prerequisiteSkillId: 'opinion_intro',
    sortOrder: 22,
  },
  {
    id: 'opinion_linking',
    name: 'Opinion Writing: Linking Words',
    description: 'Use linking words and phrases to connect opinion and reasons',
    domainCode: 'W',
    ccssCode: '3.W.1c',
    ccssDescription: 'Use linking words and phrases (e.g., because, therefore, since, for example) to connect opinion and reasons.',
    schoolDayStart: 135,
    schoolDayEnd: 140,
    prerequisiteSkillId: 'opinion_reasons',
    sortOrder: 23,
  },
  {
    id: 'informative_intro',
    name: 'Informative Writing: Introduction',
    description: 'Introduce a topic and group related information',
    domainCode: 'W',
    ccssCode: '3.W.2a',
    ccssDescription: 'Introduce a topic and group related information together; include illustrations when useful.',
    schoolDayStart: 141,
    schoolDayEnd: 147,
    prerequisiteSkillId: 'opinion_linking',
    sortOrder: 24,
  },
  {
    id: 'informative_facts',
    name: 'Informative Writing: Facts & Details',
    description: 'Develop the topic with facts, definitions, and details',
    domainCode: 'W',
    ccssCode: '3.W.2b',
    ccssDescription: 'Develop the topic with facts, definitions, and details.',
    schoolDayStart: 148,
    schoolDayEnd: 154,
    prerequisiteSkillId: 'informative_intro',
    sortOrder: 25,
  },
  {
    id: 'informative_conclusion',
    name: 'Informative Writing: Conclusion',
    description: 'Provide a concluding statement or section',
    domainCode: 'W',
    ccssCode: '3.W.2d',
    ccssDescription: 'Provide a concluding statement or section.',
    schoolDayStart: 155,
    schoolDayEnd: 160,
    prerequisiteSkillId: 'informative_facts',
    sortOrder: 26,
  },
  {
    id: 'narrative_situation',
    name: 'Narrative Writing: Situation',
    description: 'Establish a situation and introduce a narrator/characters',
    domainCode: 'W',
    ccssCode: '3.W.3a',
    ccssDescription: 'Establish a situation and introduce a narrator and/or characters; organize an event sequence.',
    schoolDayStart: 161,
    schoolDayEnd: 167,
    prerequisiteSkillId: 'informative_conclusion',
    sortOrder: 27,
  },
  {
    id: 'narrative_dialogue',
    name: 'Narrative Writing: Dialogue & Description',
    description: 'Use dialogue and descriptions to develop experiences and events',
    domainCode: 'W',
    ccssCode: '3.W.3b',
    ccssDescription: 'Use dialogue and descriptions of actions, thoughts, and feelings to develop experiences and events or show the response of characters.',
    schoolDayStart: 168,
    schoolDayEnd: 174,
    prerequisiteSkillId: 'narrative_situation',
    sortOrder: 28,
  },
  {
    id: 'narrative_sequence',
    name: 'Narrative Writing: Sequence',
    description: 'Use temporal words and phrases to signal event order',
    domainCode: 'W',
    ccssCode: '3.W.3c',
    ccssDescription: 'Use temporal words and phrases to signal event order.',
    schoolDayStart: 175,
    schoolDayEnd: 180,
    prerequisiteSkillId: 'narrative_dialogue',
    sortOrder: 29,
  },
  {
    id: 'writing_process',
    name: 'Writing Process',
    description: 'Plan, revise, and edit writing with guidance',
    domainCode: 'W',
    ccssCode: '3.W.5',
    ccssDescription: 'With guidance and support from peers and adults, develop and strengthen writing by planning, revising, and editing.',
    schoolDayStart: 181,
    schoolDayEnd: 188,
    prerequisiteSkillId: 'narrative_sequence',
    sortOrder: 30,
  },

  // ============================================================================
  // LANGUAGE (3.L) - Days 189-273
  // ============================================================================

  {
    id: 'nouns_pronouns',
    name: 'Nouns & Pronouns',
    description: 'Explain the function of nouns and pronouns',
    domainCode: 'L',
    ccssCode: '3.L.1a',
    ccssDescription: 'Explain the function of nouns, pronouns, verbs, adjectives, and adverbs in general and their functions in particular sentences.',
    schoolDayStart: 189,
    schoolDayEnd: 196,
    prerequisiteSkillId: 'writing_process',
    sortOrder: 31,
  },
  {
    id: 'verbs_adjectives',
    name: 'Verbs & Adjectives',
    description: 'Explain the function of verbs and adjectives',
    domainCode: 'L',
    ccssCode: '3.L.1a',
    ccssDescription: 'Explain the function of nouns, pronouns, verbs, adjectives, and adverbs in general and their functions in particular sentences.',
    schoolDayStart: 197,
    schoolDayEnd: 204,
    prerequisiteSkillId: 'nouns_pronouns',
    sortOrder: 32,
  },
  {
    id: 'adverbs',
    name: 'Adverbs',
    description: 'Explain the function of adverbs and use them correctly',
    domainCode: 'L',
    ccssCode: '3.L.1a',
    ccssDescription: 'Explain the function of nouns, pronouns, verbs, adjectives, and adverbs in general and their functions in particular sentences.',
    schoolDayStart: 205,
    schoolDayEnd: 210,
    prerequisiteSkillId: 'verbs_adjectives',
    sortOrder: 33,
  },
  {
    id: 'plural_nouns_regular',
    name: 'Regular Plural Nouns',
    description: 'Form and use regular plural nouns',
    domainCode: 'L',
    ccssCode: '3.L.1b',
    ccssDescription: 'Form and use regular and irregular plural nouns.',
    schoolDayStart: 211,
    schoolDayEnd: 216,
    prerequisiteSkillId: 'adverbs',
    sortOrder: 34,
  },
  {
    id: 'plural_nouns_irregular',
    name: 'Irregular Plural Nouns',
    description: 'Form and use irregular plural nouns',
    domainCode: 'L',
    ccssCode: '3.L.1b',
    ccssDescription: 'Form and use regular and irregular plural nouns.',
    schoolDayStart: 217,
    schoolDayEnd: 222,
    prerequisiteSkillId: 'plural_nouns_regular',
    sortOrder: 35,
  },
  {
    id: 'abstract_nouns',
    name: 'Abstract Nouns',
    description: 'Use abstract nouns like childhood, friendship, courage',
    domainCode: 'L',
    ccssCode: '3.L.1c',
    ccssDescription: 'Use abstract nouns (e.g., childhood).',
    schoolDayStart: 223,
    schoolDayEnd: 228,
    prerequisiteSkillId: 'plural_nouns_irregular',
    sortOrder: 36,
  },
  {
    id: 'verb_tenses',
    name: 'Verb Tenses',
    description: 'Form and use regular and irregular verb tenses',
    domainCode: 'L',
    ccssCode: '3.L.1d',
    ccssDescription: 'Form and use regular and irregular verbs.',
    schoolDayStart: 229,
    schoolDayEnd: 235,
    prerequisiteSkillId: 'abstract_nouns',
    sortOrder: 37,
  },
  {
    id: 'subject_verb_agreement',
    name: 'Subject-Verb Agreement',
    description: 'Ensure subject-verb and pronoun-antecedent agreement',
    domainCode: 'L',
    ccssCode: '3.L.1f',
    ccssDescription: 'Ensure subject-verb and pronoun-antecedent agreement.',
    schoolDayStart: 236,
    schoolDayEnd: 241,
    prerequisiteSkillId: 'verb_tenses',
    sortOrder: 38,
  },
  {
    id: 'comparative_superlative',
    name: 'Comparative & Superlative',
    description: 'Form and use comparative and superlative adjectives and adverbs',
    domainCode: 'L',
    ccssCode: '3.L.1g',
    ccssDescription: 'Form and use comparative and superlative adjectives and adverbs.',
    schoolDayStart: 242,
    schoolDayEnd: 247,
    prerequisiteSkillId: 'subject_verb_agreement',
    sortOrder: 39,
  },
  {
    id: 'conjunctions',
    name: 'Coordinating & Subordinating Conjunctions',
    description: 'Use coordinating and subordinating conjunctions',
    domainCode: 'L',
    ccssCode: '3.L.1h',
    ccssDescription: 'Use coordinating and subordinating conjunctions.',
    schoolDayStart: 248,
    schoolDayEnd: 253,
    prerequisiteSkillId: 'comparative_superlative',
    sortOrder: 40,
  },
  {
    id: 'simple_compound_sentences',
    name: 'Simple & Compound Sentences',
    description: 'Produce simple, compound, and complex sentences',
    domainCode: 'L',
    ccssCode: '3.L.1i',
    ccssDescription: 'Produce simple, compound, and complex sentences.',
    schoolDayStart: 254,
    schoolDayEnd: 259,
    prerequisiteSkillId: 'conjunctions',
    sortOrder: 41,
  },
  {
    id: 'capitalization',
    name: 'Capitalization',
    description: 'Capitalize appropriate words in titles',
    domainCode: 'L',
    ccssCode: '3.L.2a',
    ccssDescription: 'Capitalize appropriate words in titles.',
    schoolDayStart: 260,
    schoolDayEnd: 264,
    prerequisiteSkillId: 'simple_compound_sentences',
    sortOrder: 42,
  },
  {
    id: 'commas_addresses',
    name: 'Commas in Addresses',
    description: 'Use commas in addresses',
    domainCode: 'L',
    ccssCode: '3.L.2b',
    ccssDescription: 'Use commas in addresses.',
    schoolDayStart: 265,
    schoolDayEnd: 268,
    prerequisiteSkillId: 'capitalization',
    sortOrder: 43,
  },
  {
    id: 'commas_dialogue',
    name: 'Commas in Dialogue',
    description: 'Use commas and quotation marks in dialogue',
    domainCode: 'L',
    ccssCode: '3.L.2c',
    ccssDescription: 'Use commas and quotation marks in dialogue.',
    schoolDayStart: 269,
    schoolDayEnd: 273,
    prerequisiteSkillId: 'commas_addresses',
    sortOrder: 44,
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getELASkillById(id: string): Skill | undefined {
  return grade3ELASkills.find(s => s.id === id);
}

export function getELASkillsByDomain(domainCode: string): Skill[] {
  return grade3ELASkills.filter(s => s.domainCode === domainCode);
}

export function getELASkillsForDay(day: number): Skill[] {
  return grade3ELASkills.filter(
    s => s.schoolDayStart <= day && s.schoolDayEnd >= day
  );
}

export function getELASkillPrerequisiteChain(skillId: string): Skill[] {
  const chain: Skill[] = [];
  let current = getELASkillById(skillId);

  while (current?.prerequisiteSkillId) {
    const prereq = getELASkillById(current.prerequisiteSkillId);
    if (prereq) {
      chain.unshift(prereq);
      current = prereq;
    } else {
      break;
    }
  }

  return chain;
}
