/**
 * Grade 3 Lessons - Themed Content
 * ~160 lessons (70 Math + 90 ELA) with themed names and review skill references
 */

import { Lesson, ThemeCode } from './types';

// ============================================================================
// THEME ROTATION HELPER
// ============================================================================

const themeRotation: ThemeCode[] = [
  'treasure_hunt',
  'space_explorer',
  'animal_kingdom',
  'kitchen_chef',
  'builders_workshop',
  'sports_champion',
  'detective_mystery',
  'garden_explorer',
];

function getTheme(index: number): ThemeCode {
  return themeRotation[index % themeRotation.length];
}

// ============================================================================
// GRADE 3 MATH LESSONS
// ============================================================================

export const grade3MathLessons: Lesson[] = [
  // Operations & Algebraic Thinking (3.OA)
  {
    id: 'math_3_oa_1_1',
    skillId: 'multiplication_concept',
    name: 'Understanding Multiplication as Equal Groups',
    displayName: 'Counting Pirate Gold Coins',
    description: 'Learn that multiplication means adding equal groups together',
    theme: 'treasure_hunt',
    themeDescription: 'Help Captain Jack count his treasure by grouping gold coins!',
    reviewSkill1Id: null,
    reviewSkill2Id: null,
    sortOrder: 1,
  },
  {
    id: 'math_3_oa_1_2',
    skillId: 'multiplication_concept',
    name: 'Writing Multiplication Equations',
    displayName: 'Rocket Fuel Calculations',
    description: 'Write multiplication equations from equal groups',
    theme: 'space_explorer',
    themeDescription: 'Calculate how much fuel each rocket needs for the mission!',
    reviewSkill1Id: null,
    reviewSkill2Id: null,
    sortOrder: 2,
  },
  {
    id: 'math_3_oa_2_1',
    skillId: 'multiplication_arrays',
    name: 'Arrays and Multiplication',
    displayName: 'Zoo Animal Counting',
    description: 'Use rectangular arrays to model multiplication',
    theme: 'animal_kingdom',
    themeDescription: 'Count the animals in their enclosures using rows and columns!',
    reviewSkill1Id: 'multiplication_concept',
    reviewSkill2Id: null,
    sortOrder: 3,
  },
  {
    id: 'math_3_oa_2_2',
    skillId: 'multiplication_arrays',
    name: 'Drawing Arrays',
    displayName: 'Chef\'s Muffin Trays',
    description: 'Draw arrays to represent multiplication problems',
    theme: 'kitchen_chef',
    themeDescription: 'Help the chef arrange muffins in perfect rows on baking trays!',
    reviewSkill1Id: 'multiplication_concept',
    reviewSkill2Id: null,
    sortOrder: 4,
  },
  {
    id: 'math_3_oa_3_1',
    skillId: 'division_concept',
    name: 'Division as Equal Sharing',
    displayName: 'Sharing Sports Equipment',
    description: 'Understand division as splitting into equal shares',
    theme: 'sports_champion',
    themeDescription: 'Share sports equipment equally among team members!',
    reviewSkill1Id: 'multiplication_arrays',
    reviewSkill2Id: 'multiplication_concept',
    sortOrder: 5,
  },
  {
    id: 'math_3_oa_3_2',
    skillId: 'division_concept',
    name: 'Division Equations',
    displayName: 'Mystery Clue Distribution',
    description: 'Write and solve division equations',
    theme: 'detective_mystery',
    themeDescription: 'Divide the clues equally among the detective teams!',
    reviewSkill1Id: 'multiplication_arrays',
    reviewSkill2Id: 'multiplication_concept',
    sortOrder: 6,
  },
  {
    id: 'math_3_oa_4_1',
    skillId: 'division_partitioning',
    name: 'Division as Equal Groups',
    displayName: 'Planting Garden Seeds',
    description: 'Determine how many groups can be made',
    theme: 'garden_explorer',
    themeDescription: 'Plant seeds in equal groups across the garden beds!',
    reviewSkill1Id: 'division_concept',
    reviewSkill2Id: 'multiplication_arrays',
    sortOrder: 7,
  },
  {
    id: 'math_3_oa_4_2',
    skillId: 'division_partitioning',
    name: 'Arrays and Division',
    displayName: 'Treasure Chest Organization',
    description: 'Use arrays to understand division',
    theme: 'treasure_hunt',
    themeDescription: 'Organize treasure into equal piles for the pirate crew!',
    reviewSkill1Id: 'division_concept',
    reviewSkill2Id: 'multiplication_arrays',
    sortOrder: 8,
  },
  {
    id: 'math_3_oa_5_1',
    skillId: 'mult_div_word_problems',
    name: 'Multiplication Word Problems',
    displayName: 'Space Station Supplies',
    description: 'Solve word problems using multiplication',
    theme: 'space_explorer',
    themeDescription: 'Calculate supplies needed for the space station crew!',
    reviewSkill1Id: 'division_partitioning',
    reviewSkill2Id: 'division_concept',
    sortOrder: 9,
  },
  {
    id: 'math_3_oa_5_2',
    skillId: 'mult_div_word_problems',
    name: 'Division Word Problems',
    displayName: 'Animal Feeding Time',
    description: 'Solve word problems using division',
    theme: 'animal_kingdom',
    themeDescription: 'Figure out how much food each animal gets at feeding time!',
    reviewSkill1Id: 'division_partitioning',
    reviewSkill2Id: 'division_concept',
    sortOrder: 10,
  },
  {
    id: 'math_3_oa_6_1',
    skillId: 'unknown_factors',
    name: 'Finding Unknown Factors',
    displayName: 'Recipe Mystery Ingredients',
    description: 'Solve for unknown factors in multiplication',
    theme: 'kitchen_chef',
    themeDescription: 'Find the missing ingredient amounts in the recipe!',
    reviewSkill1Id: 'mult_div_word_problems',
    reviewSkill2Id: 'division_partitioning',
    sortOrder: 11,
  },
  {
    id: 'math_3_oa_6_2',
    skillId: 'unknown_factors',
    name: 'Unknown Numbers in Division',
    displayName: 'Building Block Puzzles',
    description: 'Find unknown numbers in division equations',
    theme: 'builders_workshop',
    themeDescription: 'Figure out how many blocks are needed to complete the structure!',
    reviewSkill1Id: 'mult_div_word_problems',
    reviewSkill2Id: 'division_partitioning',
    sortOrder: 12,
  },
  {
    id: 'math_3_oa_7_1',
    skillId: 'commutative_property',
    name: 'Commutative Property of Multiplication',
    displayName: 'Championship Point Scoring',
    description: 'Learn that order doesn\'t matter in multiplication',
    theme: 'sports_champion',
    themeDescription: 'Discover that scoring points works the same way in any order!',
    reviewSkill1Id: 'unknown_factors',
    reviewSkill2Id: 'mult_div_word_problems',
    sortOrder: 13,
  },
  {
    id: 'math_3_oa_7_2',
    skillId: 'commutative_property',
    name: 'Using the Commutative Property',
    displayName: 'Detective Number Patterns',
    description: 'Apply the commutative property to solve problems',
    theme: 'detective_mystery',
    themeDescription: 'Crack the code by understanding how numbers can switch places!',
    reviewSkill1Id: 'unknown_factors',
    reviewSkill2Id: 'mult_div_word_problems',
    sortOrder: 14,
  },
  {
    id: 'math_3_oa_8_1',
    skillId: 'associative_property',
    name: 'Associative Property of Multiplication',
    displayName: 'Garden Plot Planning',
    description: 'Group factors in different ways to multiply',
    theme: 'garden_explorer',
    themeDescription: 'Plan garden plots by grouping plants in different ways!',
    reviewSkill1Id: 'commutative_property',
    reviewSkill2Id: 'unknown_factors',
    sortOrder: 15,
  },
  {
    id: 'math_3_oa_8_2',
    skillId: 'associative_property',
    name: 'Grouping to Multiply',
    displayName: 'Pirate Crew Counting',
    description: 'Use grouping strategies to multiply three numbers',
    theme: 'treasure_hunt',
    themeDescription: 'Count the pirate crew by grouping them in clever ways!',
    reviewSkill1Id: 'commutative_property',
    reviewSkill2Id: 'unknown_factors',
    sortOrder: 16,
  },
  {
    id: 'math_3_oa_9_1',
    skillId: 'distributive_property',
    name: 'Distributive Property',
    displayName: 'Space Cargo Loading',
    description: 'Break apart numbers to make multiplication easier',
    theme: 'space_explorer',
    themeDescription: 'Load cargo by breaking shipments into smaller groups!',
    reviewSkill1Id: 'associative_property',
    reviewSkill2Id: 'commutative_property',
    sortOrder: 17,
  },
  {
    id: 'math_3_oa_9_2',
    skillId: 'distributive_property',
    name: 'Using the Distributive Property',
    displayName: 'Animal Habitat Counting',
    description: 'Apply the distributive property to solve problems',
    theme: 'animal_kingdom',
    themeDescription: 'Count animals by breaking habitats into sections!',
    reviewSkill1Id: 'associative_property',
    reviewSkill2Id: 'commutative_property',
    sortOrder: 18,
  },
  {
    id: 'math_3_oa_10_1',
    skillId: 'division_as_unknown',
    name: 'Division as Unknown Factor Problem',
    displayName: 'Chef\'s Portion Planning',
    description: 'Understand division using multiplication facts',
    theme: 'kitchen_chef',
    themeDescription: 'Figure out portion sizes using what you know about multiplication!',
    reviewSkill1Id: 'distributive_property',
    reviewSkill2Id: 'associative_property',
    sortOrder: 19,
  },
  {
    id: 'math_3_oa_10_2',
    skillId: 'division_as_unknown',
    name: 'Relating Multiplication and Division',
    displayName: 'Building Supply Orders',
    description: 'Use fact families to solve division problems',
    theme: 'builders_workshop',
    themeDescription: 'Calculate supply orders using multiplication and division together!',
    reviewSkill1Id: 'distributive_property',
    reviewSkill2Id: 'associative_property',
    sortOrder: 20,
  },
  {
    id: 'math_3_oa_11_1',
    skillId: 'fluency_within_100',
    name: 'Multiplication Facts Practice',
    displayName: 'Sports Statistics Master',
    description: 'Build fluency with multiplication facts',
    theme: 'sports_champion',
    themeDescription: 'Become a statistics master by knowing your multiplication facts!',
    reviewSkill1Id: 'division_as_unknown',
    reviewSkill2Id: 'distributive_property',
    sortOrder: 21,
  },
  {
    id: 'math_3_oa_11_2',
    skillId: 'fluency_within_100',
    name: 'Division Facts Practice',
    displayName: 'Detective Quick Calculations',
    description: 'Build fluency with division facts',
    theme: 'detective_mystery',
    themeDescription: 'Solve mysteries faster with quick division skills!',
    reviewSkill1Id: 'division_as_unknown',
    reviewSkill2Id: 'distributive_property',
    sortOrder: 22,
  },
  {
    id: 'math_3_oa_12_1',
    skillId: 'two_step_equations',
    name: 'Two-Step Word Problems',
    displayName: 'Garden Harvest Planning',
    description: 'Solve problems requiring two operations',
    theme: 'garden_explorer',
    themeDescription: 'Plan your harvest using multiple calculations!',
    reviewSkill1Id: 'fluency_within_100',
    reviewSkill2Id: 'division_as_unknown',
    sortOrder: 23,
  },
  {
    id: 'math_3_oa_12_2',
    skillId: 'two_step_equations',
    name: 'Equations with Letters',
    displayName: 'Treasure Map Coordinates',
    description: 'Write equations with letters for unknown quantities',
    theme: 'treasure_hunt',
    themeDescription: 'Find treasure using X to mark the spot in your equations!',
    reviewSkill1Id: 'fluency_within_100',
    reviewSkill2Id: 'division_as_unknown',
    sortOrder: 24,
  },
  {
    id: 'math_3_oa_13_1',
    skillId: 'arithmetic_patterns',
    name: 'Patterns in Multiplication',
    displayName: 'Space Navigation Patterns',
    description: 'Identify patterns in the multiplication table',
    theme: 'space_explorer',
    themeDescription: 'Navigate through space by recognizing number patterns!',
    reviewSkill1Id: 'two_step_equations',
    reviewSkill2Id: 'fluency_within_100',
    sortOrder: 25,
  },
  {
    id: 'math_3_oa_13_2',
    skillId: 'arithmetic_patterns',
    name: 'Patterns in Addition',
    displayName: 'Animal Migration Patterns',
    description: 'Identify and explain patterns in addition',
    theme: 'animal_kingdom',
    themeDescription: 'Track animal migrations by understanding number patterns!',
    reviewSkill1Id: 'two_step_equations',
    reviewSkill2Id: 'fluency_within_100',
    sortOrder: 26,
  },

  // Number & Operations in Base Ten (3.NBT)
  {
    id: 'math_3_nbt_1_1',
    skillId: 'rounding_10_100',
    name: 'Rounding to the Nearest 10',
    displayName: 'Recipe Rounding',
    description: 'Round whole numbers to the nearest 10',
    theme: 'kitchen_chef',
    themeDescription: 'Round ingredient amounts to make cooking easier!',
    reviewSkill1Id: 'arithmetic_patterns',
    reviewSkill2Id: 'two_step_equations',
    sortOrder: 27,
  },
  {
    id: 'math_3_nbt_1_2',
    skillId: 'rounding_10_100',
    name: 'Rounding to the Nearest 100',
    displayName: 'Building Material Estimates',
    description: 'Round whole numbers to the nearest 100',
    theme: 'builders_workshop',
    themeDescription: 'Estimate building materials by rounding to the nearest hundred!',
    reviewSkill1Id: 'arithmetic_patterns',
    reviewSkill2Id: 'two_step_equations',
    sortOrder: 28,
  },
  {
    id: 'math_3_nbt_2_1',
    skillId: 'add_subtract_1000',
    name: 'Adding within 1000',
    displayName: 'Championship Score Totals',
    description: 'Add numbers within 1000 using strategies',
    theme: 'sports_champion',
    themeDescription: 'Calculate total championship points for your team!',
    reviewSkill1Id: 'rounding_10_100',
    reviewSkill2Id: 'arithmetic_patterns',
    sortOrder: 29,
  },
  {
    id: 'math_3_nbt_2_2',
    skillId: 'add_subtract_1000',
    name: 'Subtracting within 1000',
    displayName: 'Evidence Analysis',
    description: 'Subtract numbers within 1000 using strategies',
    theme: 'detective_mystery',
    themeDescription: 'Analyze evidence by calculating differences in data!',
    reviewSkill1Id: 'rounding_10_100',
    reviewSkill2Id: 'arithmetic_patterns',
    sortOrder: 30,
  },
  {
    id: 'math_3_nbt_3_1',
    skillId: 'multiply_multiples_10',
    name: 'Multiplying by 10',
    displayName: 'Garden Bed Expansion',
    description: 'Multiply one-digit numbers by 10',
    theme: 'garden_explorer',
    themeDescription: 'Expand your garden by multiplying planting rows!',
    reviewSkill1Id: 'add_subtract_1000',
    reviewSkill2Id: 'rounding_10_100',
    sortOrder: 31,
  },
  {
    id: 'math_3_nbt_3_2',
    skillId: 'multiply_multiples_10',
    name: 'Multiplying by Multiples of 10',
    displayName: 'Treasure Vault Counting',
    description: 'Multiply by 20, 30, 40, etc.',
    theme: 'treasure_hunt',
    themeDescription: 'Count treasure in the vault using multiplication shortcuts!',
    reviewSkill1Id: 'add_subtract_1000',
    reviewSkill2Id: 'rounding_10_100',
    sortOrder: 32,
  },

  // Number & Operations—Fractions (3.NF)
  {
    id: 'math_3_nf_1_1',
    skillId: 'unit_fractions',
    name: 'Understanding Unit Fractions',
    displayName: 'Space Ration Distribution',
    description: 'Learn what unit fractions represent',
    theme: 'space_explorer',
    themeDescription: 'Divide space rations into equal parts for the astronauts!',
    reviewSkill1Id: 'multiply_multiples_10',
    reviewSkill2Id: 'add_subtract_1000',
    sortOrder: 33,
  },
  {
    id: 'math_3_nf_1_2',
    skillId: 'unit_fractions',
    name: 'Naming Unit Fractions',
    displayName: 'Animal Habitat Divisions',
    description: 'Read and write unit fractions',
    theme: 'animal_kingdom',
    themeDescription: 'Divide animal habitats into equal sections!',
    reviewSkill1Id: 'multiply_multiples_10',
    reviewSkill2Id: 'add_subtract_1000',
    sortOrder: 34,
  },
  {
    id: 'math_3_nf_2_1',
    skillId: 'fractions_number_line',
    name: 'Fractions on Number Lines',
    displayName: 'Recipe Measurements',
    description: 'Place fractions on a number line',
    theme: 'kitchen_chef',
    themeDescription: 'Measure ingredients precisely using fraction number lines!',
    reviewSkill1Id: 'unit_fractions',
    reviewSkill2Id: 'multiply_multiples_10',
    sortOrder: 35,
  },
  {
    id: 'math_3_nf_2_2',
    skillId: 'fractions_number_line',
    name: 'Reading Number Lines',
    displayName: 'Building Measurements',
    description: 'Identify fractions shown on number lines',
    theme: 'builders_workshop',
    themeDescription: 'Read precise measurements from building blueprints!',
    reviewSkill1Id: 'unit_fractions',
    reviewSkill2Id: 'multiply_multiples_10',
    sortOrder: 36,
  },
  {
    id: 'math_3_nf_3_1',
    skillId: 'fractions_partition_place',
    name: 'Partitioning Number Lines',
    displayName: 'Race Track Sections',
    description: 'Divide number lines into equal parts',
    theme: 'sports_champion',
    themeDescription: 'Mark race track sections using equal divisions!',
    reviewSkill1Id: 'fractions_number_line',
    reviewSkill2Id: 'unit_fractions',
    sortOrder: 37,
  },
  {
    id: 'math_3_nf_3_2',
    skillId: 'fractions_partition_place',
    name: 'Locating Fractions',
    displayName: 'Detective Distance Tracking',
    description: 'Find exact positions of fractions',
    theme: 'detective_mystery',
    themeDescription: 'Track suspect locations using precise fraction distances!',
    reviewSkill1Id: 'fractions_number_line',
    reviewSkill2Id: 'unit_fractions',
    sortOrder: 38,
  },
  {
    id: 'math_3_nf_4_1',
    skillId: 'equivalent_fractions',
    name: 'Understanding Equivalent Fractions',
    displayName: 'Garden Plot Divisions',
    description: 'Recognize fractions that are equal',
    theme: 'garden_explorer',
    themeDescription: 'Discover that garden plots can be divided in different but equal ways!',
    reviewSkill1Id: 'fractions_partition_place',
    reviewSkill2Id: 'fractions_number_line',
    sortOrder: 39,
  },
  {
    id: 'math_3_nf_4_2',
    skillId: 'equivalent_fractions',
    name: 'Generating Equivalent Fractions',
    displayName: 'Treasure Share Trading',
    description: 'Create equivalent fractions',
    theme: 'treasure_hunt',
    themeDescription: 'Trade treasure shares that are equal in different ways!',
    reviewSkill1Id: 'fractions_partition_place',
    reviewSkill2Id: 'fractions_number_line',
    sortOrder: 40,
  },
  {
    id: 'math_3_nf_5_1',
    skillId: 'whole_as_fractions',
    name: 'Whole Numbers as Fractions',
    displayName: 'Space Station Modules',
    description: 'Express whole numbers as fractions',
    theme: 'space_explorer',
    themeDescription: 'Understand whole station modules as complete units!',
    reviewSkill1Id: 'equivalent_fractions',
    reviewSkill2Id: 'fractions_partition_place',
    sortOrder: 41,
  },
  {
    id: 'math_3_nf_5_2',
    skillId: 'whole_as_fractions',
    name: 'Fractions Equal to Whole Numbers',
    displayName: 'Complete Animal Families',
    description: 'Recognize fractions that equal whole numbers',
    theme: 'animal_kingdom',
    themeDescription: 'See how animal family groups can be shown as fractions!',
    reviewSkill1Id: 'equivalent_fractions',
    reviewSkill2Id: 'fractions_partition_place',
    sortOrder: 42,
  },
  {
    id: 'math_3_nf_6_1',
    skillId: 'comparing_fractions',
    name: 'Comparing Fractions with Same Denominator',
    displayName: 'Recipe Comparisons',
    description: 'Compare fractions with the same bottom number',
    theme: 'kitchen_chef',
    themeDescription: 'Compare recipe amounts to see which uses more!',
    reviewSkill1Id: 'whole_as_fractions',
    reviewSkill2Id: 'equivalent_fractions',
    sortOrder: 43,
  },
  {
    id: 'math_3_nf_6_2',
    skillId: 'comparing_fractions',
    name: 'Comparing Fractions with Same Numerator',
    displayName: 'Building Material Comparisons',
    description: 'Compare fractions with the same top number',
    theme: 'builders_workshop',
    themeDescription: 'Compare building materials to find the larger piece!',
    reviewSkill1Id: 'whole_as_fractions',
    reviewSkill2Id: 'equivalent_fractions',
    sortOrder: 44,
  },

  // Measurement & Data (3.MD)
  {
    id: 'math_3_md_1_1',
    skillId: 'time_elapsed',
    name: 'Telling Time to the Minute',
    displayName: 'Game Time Tracking',
    description: 'Read and write time to the nearest minute',
    theme: 'sports_champion',
    themeDescription: 'Track game times down to the exact minute!',
    reviewSkill1Id: 'comparing_fractions',
    reviewSkill2Id: 'whole_as_fractions',
    sortOrder: 45,
  },
  {
    id: 'math_3_md_1_2',
    skillId: 'time_elapsed',
    name: 'Elapsed Time',
    displayName: 'Case File Timelines',
    description: 'Calculate time intervals',
    theme: 'detective_mystery',
    themeDescription: 'Create timelines to solve when events happened!',
    reviewSkill1Id: 'comparing_fractions',
    reviewSkill2Id: 'whole_as_fractions',
    sortOrder: 46,
  },
  {
    id: 'math_3_md_2_1',
    skillId: 'liquid_mass',
    name: 'Measuring Liquid Volume',
    displayName: 'Garden Watering',
    description: 'Measure liquids in liters',
    theme: 'garden_explorer',
    themeDescription: 'Measure water for your garden plants!',
    reviewSkill1Id: 'time_elapsed',
    reviewSkill2Id: 'comparing_fractions',
    sortOrder: 47,
  },
  {
    id: 'math_3_md_2_2',
    skillId: 'liquid_mass',
    name: 'Measuring Mass',
    displayName: 'Treasure Weighing',
    description: 'Measure mass in grams and kilograms',
    theme: 'treasure_hunt',
    themeDescription: 'Weigh treasure to know how much you found!',
    reviewSkill1Id: 'time_elapsed',
    reviewSkill2Id: 'comparing_fractions',
    sortOrder: 48,
  },
  {
    id: 'math_3_md_3_1',
    skillId: 'picture_graphs',
    name: 'Reading Picture Graphs',
    displayName: 'Space Mission Data',
    description: 'Interpret data from picture graphs',
    theme: 'space_explorer',
    themeDescription: 'Read mission data from picture graphs!',
    reviewSkill1Id: 'liquid_mass',
    reviewSkill2Id: 'time_elapsed',
    sortOrder: 49,
  },
  {
    id: 'math_3_md_3_2',
    skillId: 'picture_graphs',
    name: 'Creating Picture Graphs',
    displayName: 'Animal Population Charts',
    description: 'Draw scaled picture graphs',
    theme: 'animal_kingdom',
    themeDescription: 'Create picture graphs to show animal populations!',
    reviewSkill1Id: 'liquid_mass',
    reviewSkill2Id: 'time_elapsed',
    sortOrder: 50,
  },
  {
    id: 'math_3_md_4_1',
    skillId: 'bar_graphs',
    name: 'Reading Bar Graphs',
    displayName: 'Recipe Popularity Survey',
    description: 'Interpret data from bar graphs',
    theme: 'kitchen_chef',
    themeDescription: 'Read bar graphs to find the most popular recipes!',
    reviewSkill1Id: 'picture_graphs',
    reviewSkill2Id: 'liquid_mass',
    sortOrder: 51,
  },
  {
    id: 'math_3_md_4_2',
    skillId: 'bar_graphs',
    name: 'Creating Bar Graphs',
    displayName: 'Building Project Tracking',
    description: 'Draw scaled bar graphs',
    theme: 'builders_workshop',
    themeDescription: 'Track project progress with bar graphs!',
    reviewSkill1Id: 'picture_graphs',
    reviewSkill2Id: 'liquid_mass',
    sortOrder: 52,
  },
  {
    id: 'math_3_md_5_1',
    skillId: 'line_plots',
    name: 'Understanding Line Plots',
    displayName: 'Athletic Performance Data',
    description: 'Read and interpret line plots',
    theme: 'sports_champion',
    themeDescription: 'Track athletic performance with line plots!',
    reviewSkill1Id: 'bar_graphs',
    reviewSkill2Id: 'picture_graphs',
    sortOrder: 53,
  },
  {
    id: 'math_3_md_5_2',
    skillId: 'line_plots',
    name: 'Creating Line Plots',
    displayName: 'Evidence Measurement Data',
    description: 'Generate data and create line plots',
    theme: 'detective_mystery',
    themeDescription: 'Plot evidence measurements to find patterns!',
    reviewSkill1Id: 'bar_graphs',
    reviewSkill2Id: 'picture_graphs',
    sortOrder: 54,
  },
  {
    id: 'math_3_md_6_1',
    skillId: 'area_concept',
    name: 'What is Area?',
    displayName: 'Garden Bed Planning',
    description: 'Understand area as covering with unit squares',
    theme: 'garden_explorer',
    themeDescription: 'Plan garden beds by understanding how much space they cover!',
    reviewSkill1Id: 'line_plots',
    reviewSkill2Id: 'bar_graphs',
    sortOrder: 55,
  },
  {
    id: 'math_3_md_6_2',
    skillId: 'area_concept',
    name: 'Square Units',
    displayName: 'Treasure Map Grids',
    description: 'Measure area using square units',
    theme: 'treasure_hunt',
    themeDescription: 'Measure treasure island areas using map grid squares!',
    reviewSkill1Id: 'line_plots',
    reviewSkill2Id: 'bar_graphs',
    sortOrder: 56,
  },
  {
    id: 'math_3_md_7_1',
    skillId: 'area_counting',
    name: 'Counting Square Units',
    displayName: 'Space Station Floor Plans',
    description: 'Find area by counting unit squares',
    theme: 'space_explorer',
    themeDescription: 'Calculate space station room sizes by counting floor tiles!',
    reviewSkill1Id: 'area_concept',
    reviewSkill2Id: 'line_plots',
    sortOrder: 57,
  },
  {
    id: 'math_3_md_7_2',
    skillId: 'area_counting',
    name: 'Measuring Area',
    displayName: 'Animal Enclosure Sizing',
    description: 'Measure areas of different shapes',
    theme: 'animal_kingdom',
    themeDescription: 'Measure animal enclosures to make sure they are big enough!',
    reviewSkill1Id: 'area_concept',
    reviewSkill2Id: 'line_plots',
    sortOrder: 58,
  },
  {
    id: 'math_3_md_8_1',
    skillId: 'area_multiplication',
    name: 'Area and Multiplication',
    displayName: 'Kitchen Tile Calculations',
    description: 'Calculate area using multiplication',
    theme: 'kitchen_chef',
    themeDescription: 'Calculate how many tiles cover the kitchen floor!',
    reviewSkill1Id: 'area_counting',
    reviewSkill2Id: 'area_concept',
    sortOrder: 59,
  },
  {
    id: 'math_3_md_8_2',
    skillId: 'area_multiplication',
    name: 'Area of Rectangles',
    displayName: 'Construction Area Calculations',
    description: 'Find area by multiplying side lengths',
    theme: 'builders_workshop',
    themeDescription: 'Calculate construction areas by multiplying length and width!',
    reviewSkill1Id: 'area_counting',
    reviewSkill2Id: 'area_concept',
    sortOrder: 60,
  },
  {
    id: 'math_3_md_9_1',
    skillId: 'perimeter',
    name: 'Understanding Perimeter',
    displayName: 'Race Track Borders',
    description: 'Find perimeter by adding side lengths',
    theme: 'sports_champion',
    themeDescription: 'Measure the border of race tracks to find the perimeter!',
    reviewSkill1Id: 'area_multiplication',
    reviewSkill2Id: 'area_counting',
    sortOrder: 61,
  },
  {
    id: 'math_3_md_9_2',
    skillId: 'perimeter',
    name: 'Finding Missing Side Lengths',
    displayName: 'Crime Scene Borders',
    description: 'Use perimeter to find unknown sides',
    theme: 'detective_mystery',
    themeDescription: 'Calculate missing fence lengths at the crime scene!',
    reviewSkill1Id: 'area_multiplication',
    reviewSkill2Id: 'area_counting',
    sortOrder: 62,
  },

  // Geometry (3.G)
  {
    id: 'math_3_g_1_1',
    skillId: 'shape_categories',
    name: 'Shape Attributes',
    displayName: 'Garden Bed Shapes',
    description: 'Identify shapes by their attributes',
    theme: 'garden_explorer',
    themeDescription: 'Classify garden beds by their shape attributes!',
    reviewSkill1Id: 'perimeter',
    reviewSkill2Id: 'area_multiplication',
    sortOrder: 63,
  },
  {
    id: 'math_3_g_1_2',
    skillId: 'shape_categories',
    name: 'Categorizing Shapes',
    displayName: 'Treasure Chest Shapes',
    description: 'Group shapes by shared attributes',
    theme: 'treasure_hunt',
    themeDescription: 'Sort treasure chest shapes into categories!',
    reviewSkill1Id: 'perimeter',
    reviewSkill2Id: 'area_multiplication',
    sortOrder: 64,
  },
  {
    id: 'math_3_g_2_1',
    skillId: 'quadrilaterals',
    name: 'Quadrilaterals',
    displayName: 'Spaceship Window Shapes',
    description: 'Identify and classify quadrilaterals',
    theme: 'space_explorer',
    themeDescription: 'Identify the quadrilateral shapes of spaceship windows!',
    reviewSkill1Id: 'shape_categories',
    reviewSkill2Id: 'perimeter',
    sortOrder: 65,
  },
  {
    id: 'math_3_g_2_2',
    skillId: 'quadrilaterals',
    name: 'Special Quadrilaterals',
    displayName: 'Animal Pen Designs',
    description: 'Recognize rectangles, squares, and rhombuses',
    theme: 'animal_kingdom',
    themeDescription: 'Design animal pens using different quadrilateral shapes!',
    reviewSkill1Id: 'shape_categories',
    reviewSkill2Id: 'perimeter',
    sortOrder: 66,
  },
  {
    id: 'math_3_g_3_1',
    skillId: 'partition_shapes',
    name: 'Partitioning Shapes',
    displayName: 'Pizza Slice Fractions',
    description: 'Divide shapes into equal parts',
    theme: 'kitchen_chef',
    themeDescription: 'Cut pizzas into equal fraction slices!',
    reviewSkill1Id: 'quadrilaterals',
    reviewSkill2Id: 'shape_categories',
    sortOrder: 67,
  },
  {
    id: 'math_3_g_3_2',
    skillId: 'partition_shapes',
    name: 'Equal Parts as Fractions',
    displayName: 'Floor Plan Divisions',
    description: 'Express partitioned areas as fractions',
    theme: 'builders_workshop',
    themeDescription: 'Divide floor plans into equal fraction sections!',
    reviewSkill1Id: 'quadrilaterals',
    reviewSkill2Id: 'shape_categories',
    sortOrder: 68,
  },

  // Review & Assessment
  {
    id: 'math_3_review_1',
    skillId: 'review_oa_nbt',
    name: 'Operations Review',
    displayName: 'Championship Finals Review',
    description: 'Review multiplication, division, and base ten operations',
    theme: 'sports_champion',
    themeDescription: 'Practice your operations skills for the championship finals!',
    reviewSkill1Id: 'partition_shapes',
    reviewSkill2Id: 'quadrilaterals',
    sortOrder: 69,
  },
  {
    id: 'math_3_review_2',
    skillId: 'review_nf',
    name: 'Fractions Review',
    displayName: 'Mystery Fraction Clues',
    description: 'Review all fraction concepts',
    theme: 'detective_mystery',
    themeDescription: 'Use your fraction skills to solve the final mystery!',
    reviewSkill1Id: 'review_oa_nbt',
    reviewSkill2Id: 'partition_shapes',
    sortOrder: 70,
  },
  {
    id: 'math_3_review_3',
    skillId: 'review_md',
    name: 'Measurement & Data Review',
    displayName: 'Garden Season Finale',
    description: 'Review measurement and data skills',
    theme: 'garden_explorer',
    themeDescription: 'Use all your measurement skills for the garden season finale!',
    reviewSkill1Id: 'review_nf',
    reviewSkill2Id: 'review_oa_nbt',
    sortOrder: 71,
  },
  {
    id: 'math_3_review_4',
    skillId: 'review_geometry',
    name: 'Geometry Review',
    displayName: 'Treasure Island Finale',
    description: 'Review geometry concepts',
    theme: 'treasure_hunt',
    themeDescription: 'Use geometry to find the final treasure on the island!',
    reviewSkill1Id: 'review_md',
    reviewSkill2Id: 'review_nf',
    sortOrder: 72,
  },
];

// ============================================================================
// GRADE 3 ELA LESSONS
// ============================================================================

export const grade3ELALessons: Lesson[] = [
  // Reading: Literature (3.RL)
  {
    id: 'ela_3_rl_1_1',
    skillId: 'ask_answer_lit',
    name: 'Asking Questions About Stories',
    displayName: 'Pirate Tale Questions',
    description: 'Learn to ask questions while reading literature',
    theme: 'treasure_hunt',
    themeDescription: 'Ask questions about exciting pirate adventure stories!',
    reviewSkill1Id: null,
    reviewSkill2Id: null,
    sortOrder: 1,
  },
  {
    id: 'ela_3_rl_1_2',
    skillId: 'ask_answer_lit',
    name: 'Finding Answers in Text',
    displayName: 'Space Story Evidence',
    description: 'Find evidence in the text to answer questions',
    theme: 'space_explorer',
    themeDescription: 'Find evidence in space adventure stories!',
    reviewSkill1Id: null,
    reviewSkill2Id: null,
    sortOrder: 2,
  },
  {
    id: 'ela_3_rl_2_1',
    skillId: 'recount_stories',
    name: 'Recounting Stories',
    displayName: 'Animal Fable Retelling',
    description: 'Retell stories including key details',
    theme: 'animal_kingdom',
    themeDescription: 'Retell classic animal fables in your own words!',
    reviewSkill1Id: 'ask_answer_lit',
    reviewSkill2Id: null,
    sortOrder: 3,
  },
  {
    id: 'ela_3_rl_2_2',
    skillId: 'recount_stories',
    name: 'Finding the Moral',
    displayName: 'Chef\'s Wisdom Tales',
    description: 'Determine the central message or moral',
    theme: 'kitchen_chef',
    themeDescription: 'Find the lessons in stories about chefs and cooking!',
    reviewSkill1Id: 'ask_answer_lit',
    reviewSkill2Id: null,
    sortOrder: 4,
  },
  {
    id: 'ela_3_rl_3_1',
    skillId: 'character_traits',
    name: 'Character Descriptions',
    displayName: 'Builder Hero Traits',
    description: 'Describe character traits and motivations',
    theme: 'builders_workshop',
    themeDescription: 'Describe the traits of heroic builders in stories!',
    reviewSkill1Id: 'recount_stories',
    reviewSkill2Id: 'ask_answer_lit',
    sortOrder: 5,
  },
  {
    id: 'ela_3_rl_3_2',
    skillId: 'character_traits',
    name: 'Character Actions',
    displayName: 'Sports Story Characters',
    description: 'Explain how character actions affect events',
    theme: 'sports_champion',
    themeDescription: 'See how sports characters\' choices change the story!',
    reviewSkill1Id: 'recount_stories',
    reviewSkill2Id: 'ask_answer_lit',
    sortOrder: 6,
  },
  {
    id: 'ela_3_rl_4_1',
    skillId: 'literal_nonliteral',
    name: 'Literal Language',
    displayName: 'Detective Word Meanings',
    description: 'Understand words with their exact meanings',
    theme: 'detective_mystery',
    themeDescription: 'Decode the exact meaning of words in mystery stories!',
    reviewSkill1Id: 'character_traits',
    reviewSkill2Id: 'recount_stories',
    sortOrder: 7,
  },
  {
    id: 'ela_3_rl_4_2',
    skillId: 'literal_nonliteral',
    name: 'Nonliteral Language',
    displayName: 'Garden Idiom Adventures',
    description: 'Understand figurative language like idioms',
    theme: 'garden_explorer',
    themeDescription: 'Discover the hidden meanings in garden expressions!',
    reviewSkill1Id: 'character_traits',
    reviewSkill2Id: 'recount_stories',
    sortOrder: 8,
  },
  {
    id: 'ela_3_rl_5_1',
    skillId: 'story_structure',
    name: 'Story Parts',
    displayName: 'Pirate Adventure Chapters',
    description: 'Identify chapters, scenes, and stanzas',
    theme: 'treasure_hunt',
    themeDescription: 'Navigate through pirate story chapters and scenes!',
    reviewSkill1Id: 'literal_nonliteral',
    reviewSkill2Id: 'character_traits',
    sortOrder: 9,
  },
  {
    id: 'ela_3_rl_5_2',
    skillId: 'story_structure',
    name: 'Poetry Structure',
    displayName: 'Space Poetry Exploration',
    description: 'Understand poem structure with stanzas',
    theme: 'space_explorer',
    themeDescription: 'Explore the structure of poems about space!',
    reviewSkill1Id: 'literal_nonliteral',
    reviewSkill2Id: 'character_traits',
    sortOrder: 10,
  },
  {
    id: 'ela_3_rl_6_1',
    skillId: 'point_of_view_lit',
    name: 'Narrator Point of View',
    displayName: 'Animal Story Perspectives',
    description: 'Identify the narrator\'s point of view',
    theme: 'animal_kingdom',
    themeDescription: 'See animal stories from different perspectives!',
    reviewSkill1Id: 'story_structure',
    reviewSkill2Id: 'literal_nonliteral',
    sortOrder: 11,
  },
  {
    id: 'ela_3_rl_6_2',
    skillId: 'point_of_view_lit',
    name: 'Your Point of View',
    displayName: 'Recipe Story Opinions',
    description: 'Distinguish your view from the narrator\'s',
    theme: 'kitchen_chef',
    themeDescription: 'Share your opinions about cooking stories!',
    reviewSkill1Id: 'story_structure',
    reviewSkill2Id: 'literal_nonliteral',
    sortOrder: 12,
  },
  {
    id: 'ela_3_rl_7_1',
    skillId: 'illustrations_text',
    name: 'Illustrations in Stories',
    displayName: 'Builder Blueprint Pictures',
    description: 'Explain how illustrations add meaning',
    theme: 'builders_workshop',
    themeDescription: 'See how pictures help tell building stories!',
    reviewSkill1Id: 'point_of_view_lit',
    reviewSkill2Id: 'story_structure',
    sortOrder: 13,
  },
  {
    id: 'ela_3_rl_7_2',
    skillId: 'illustrations_text',
    name: 'Mood and Pictures',
    displayName: 'Sports Story Illustrations',
    description: 'See how illustrations create mood',
    theme: 'sports_champion',
    themeDescription: 'Feel the excitement through sports story pictures!',
    reviewSkill1Id: 'point_of_view_lit',
    reviewSkill2Id: 'story_structure',
    sortOrder: 14,
  },

  // Reading: Informational Text (3.RI)
  {
    id: 'ela_3_ri_1_1',
    skillId: 'ask_answer_info',
    name: 'Questions About Information',
    displayName: 'Mystery Case Questions',
    description: 'Ask questions about informational texts',
    theme: 'detective_mystery',
    themeDescription: 'Ask investigative questions about factual texts!',
    reviewSkill1Id: 'illustrations_text',
    reviewSkill2Id: 'point_of_view_lit',
    sortOrder: 15,
  },
  {
    id: 'ela_3_ri_1_2',
    skillId: 'ask_answer_info',
    name: 'Text Evidence',
    displayName: 'Garden Guide Evidence',
    description: 'Find evidence in informational texts',
    theme: 'garden_explorer',
    themeDescription: 'Find facts in gardening guides!',
    reviewSkill1Id: 'illustrations_text',
    reviewSkill2Id: 'point_of_view_lit',
    sortOrder: 16,
  },
  {
    id: 'ela_3_ri_2_1',
    skillId: 'main_idea_details',
    name: 'Main Idea',
    displayName: 'Treasure History Main Ideas',
    description: 'Determine the main idea of a text',
    theme: 'treasure_hunt',
    themeDescription: 'Find the main idea in treasure hunting history!',
    reviewSkill1Id: 'ask_answer_info',
    reviewSkill2Id: 'illustrations_text',
    sortOrder: 17,
  },
  {
    id: 'ela_3_ri_2_2',
    skillId: 'main_idea_details',
    name: 'Supporting Details',
    displayName: 'Space Exploration Facts',
    description: 'Identify key details that support the main idea',
    theme: 'space_explorer',
    themeDescription: 'Find supporting details in space exploration articles!',
    reviewSkill1Id: 'ask_answer_info',
    reviewSkill2Id: 'illustrations_text',
    sortOrder: 18,
  },
  {
    id: 'ela_3_ri_3_1',
    skillId: 'historical_scientific',
    name: 'Historical Connections',
    displayName: 'Animal History Timeline',
    description: 'Describe relationships between historical events',
    theme: 'animal_kingdom',
    themeDescription: 'Connect events in animal history!',
    reviewSkill1Id: 'main_idea_details',
    reviewSkill2Id: 'ask_answer_info',
    sortOrder: 19,
  },
  {
    id: 'ela_3_ri_3_2',
    skillId: 'historical_scientific',
    name: 'Scientific Concepts',
    displayName: 'Kitchen Science Connections',
    description: 'Understand cause and effect in science texts',
    theme: 'kitchen_chef',
    themeDescription: 'Discover scientific connections in cooking!',
    reviewSkill1Id: 'main_idea_details',
    reviewSkill2Id: 'ask_answer_info',
    sortOrder: 20,
  },
  {
    id: 'ela_3_ri_4_1',
    skillId: 'academic_vocabulary',
    name: 'Academic Words',
    displayName: 'Builder Technical Terms',
    description: 'Learn general academic vocabulary',
    theme: 'builders_workshop',
    themeDescription: 'Master the technical words builders use!',
    reviewSkill1Id: 'historical_scientific',
    reviewSkill2Id: 'main_idea_details',
    sortOrder: 21,
  },
  {
    id: 'ela_3_ri_4_2',
    skillId: 'academic_vocabulary',
    name: 'Domain-Specific Words',
    displayName: 'Sports Terminology',
    description: 'Learn subject-specific vocabulary',
    theme: 'sports_champion',
    themeDescription: 'Learn the special words used in sports!',
    reviewSkill1Id: 'historical_scientific',
    reviewSkill2Id: 'main_idea_details',
    sortOrder: 22,
  },
  {
    id: 'ela_3_ri_5_1',
    skillId: 'text_features',
    name: 'Using Text Features',
    displayName: 'Detective Handbook Features',
    description: 'Use features like headings and sidebars',
    theme: 'detective_mystery',
    themeDescription: 'Navigate detective handbooks using text features!',
    reviewSkill1Id: 'academic_vocabulary',
    reviewSkill2Id: 'historical_scientific',
    sortOrder: 23,
  },
  {
    id: 'ela_3_ri_5_2',
    skillId: 'text_features',
    name: 'Search Tools',
    displayName: 'Garden Encyclopedia Search',
    description: 'Use search tools to find information',
    theme: 'garden_explorer',
    themeDescription: 'Search garden encyclopedias efficiently!',
    reviewSkill1Id: 'academic_vocabulary',
    reviewSkill2Id: 'historical_scientific',
    sortOrder: 24,
  },
  {
    id: 'ela_3_ri_6_1',
    skillId: 'point_of_view_info',
    name: 'Author\'s Point of View',
    displayName: 'Pirate History Perspectives',
    description: 'Identify the author\'s purpose and viewpoint',
    theme: 'treasure_hunt',
    themeDescription: 'Understand how authors view pirate history!',
    reviewSkill1Id: 'text_features',
    reviewSkill2Id: 'academic_vocabulary',
    sortOrder: 25,
  },
  {
    id: 'ela_3_ri_6_2',
    skillId: 'point_of_view_info',
    name: 'Your Opinion vs. Author',
    displayName: 'Space Opinions',
    description: 'Distinguish your view from the author\'s',
    theme: 'space_explorer',
    themeDescription: 'Form your own opinions about space exploration!',
    reviewSkill1Id: 'text_features',
    reviewSkill2Id: 'academic_vocabulary',
    sortOrder: 26,
  },
  {
    id: 'ela_3_ri_7_1',
    skillId: 'visual_info',
    name: 'Reading Maps',
    displayName: 'Animal Habitat Maps',
    description: 'Use maps to understand text',
    theme: 'animal_kingdom',
    themeDescription: 'Read maps showing where animals live!',
    reviewSkill1Id: 'point_of_view_info',
    reviewSkill2Id: 'text_features',
    sortOrder: 27,
  },
  {
    id: 'ela_3_ri_7_2',
    skillId: 'visual_info',
    name: 'Reading Photographs',
    displayName: 'Recipe Photo Analysis',
    description: 'Use photographs to enhance understanding',
    theme: 'kitchen_chef',
    themeDescription: 'Learn from photos in recipe books!',
    reviewSkill1Id: 'point_of_view_info',
    reviewSkill2Id: 'text_features',
    sortOrder: 28,
  },
  {
    id: 'ela_3_ri_8_1',
    skillId: 'logical_connections',
    name: 'Comparison Connections',
    displayName: 'Building Methods Compared',
    description: 'Identify comparison relationships in text',
    theme: 'builders_workshop',
    themeDescription: 'Compare different building methods in texts!',
    reviewSkill1Id: 'visual_info',
    reviewSkill2Id: 'point_of_view_info',
    sortOrder: 29,
  },
  {
    id: 'ela_3_ri_8_2',
    skillId: 'logical_connections',
    name: 'Cause and Effect',
    displayName: 'Sports Performance Factors',
    description: 'Identify cause and effect in paragraphs',
    theme: 'sports_champion',
    themeDescription: 'Understand what causes sports success!',
    reviewSkill1Id: 'visual_info',
    reviewSkill2Id: 'point_of_view_info',
    sortOrder: 30,
  },
  {
    id: 'ela_3_ri_9_1',
    skillId: 'compare_texts',
    name: 'Comparing Two Texts',
    displayName: 'Detective Source Comparison',
    description: 'Compare key points between texts',
    theme: 'detective_mystery',
    themeDescription: 'Compare different sources like a detective!',
    reviewSkill1Id: 'logical_connections',
    reviewSkill2Id: 'visual_info',
    sortOrder: 31,
  },
  {
    id: 'ela_3_ri_9_2',
    skillId: 'compare_texts',
    name: 'Contrasting Texts',
    displayName: 'Garden Guide Differences',
    description: 'Find differences between texts on the same topic',
    theme: 'garden_explorer',
    themeDescription: 'Find differences in gardening guides!',
    reviewSkill1Id: 'logical_connections',
    reviewSkill2Id: 'visual_info',
    sortOrder: 32,
  },

  // Reading: Foundational Skills (3.RF)
  {
    id: 'ela_3_rf_1_1',
    skillId: 'phonics_decoding',
    name: 'Decoding Words',
    displayName: 'Treasure Word Decoding',
    description: 'Apply phonics to decode unfamiliar words',
    theme: 'treasure_hunt',
    themeDescription: 'Decode treasure-themed words using phonics!',
    reviewSkill1Id: 'compare_texts',
    reviewSkill2Id: 'logical_connections',
    sortOrder: 33,
  },
  {
    id: 'ela_3_rf_1_2',
    skillId: 'phonics_decoding',
    name: 'Word Attack Strategies',
    displayName: 'Space Word Challenges',
    description: 'Use multiple strategies to read words',
    theme: 'space_explorer',
    themeDescription: 'Attack challenging space vocabulary!',
    reviewSkill1Id: 'compare_texts',
    reviewSkill2Id: 'logical_connections',
    sortOrder: 34,
  },
  {
    id: 'ela_3_rf_2_1',
    skillId: 'prefixes_suffixes',
    name: 'Common Prefixes',
    displayName: 'Animal Word Beginnings',
    description: 'Identify and understand common prefixes',
    theme: 'animal_kingdom',
    themeDescription: 'Learn prefixes through animal vocabulary!',
    reviewSkill1Id: 'phonics_decoding',
    reviewSkill2Id: 'compare_texts',
    sortOrder: 35,
  },
  {
    id: 'ela_3_rf_2_2',
    skillId: 'prefixes_suffixes',
    name: 'Common Suffixes',
    displayName: 'Kitchen Word Endings',
    description: 'Identify and understand common suffixes',
    theme: 'kitchen_chef',
    themeDescription: 'Master suffixes with cooking vocabulary!',
    reviewSkill1Id: 'phonics_decoding',
    reviewSkill2Id: 'compare_texts',
    sortOrder: 36,
  },
  {
    id: 'ela_3_rf_3_1',
    skillId: 'multisyllable_words',
    name: 'Breaking Words Apart',
    displayName: 'Builder Term Syllables',
    description: 'Divide multisyllable words',
    theme: 'builders_workshop',
    themeDescription: 'Break construction words into syllables!',
    reviewSkill1Id: 'prefixes_suffixes',
    reviewSkill2Id: 'phonics_decoding',
    sortOrder: 37,
  },
  {
    id: 'ela_3_rf_3_2',
    skillId: 'multisyllable_words',
    name: 'Reading Long Words',
    displayName: 'Sports Vocabulary Mastery',
    description: 'Read multisyllable words fluently',
    theme: 'sports_champion',
    themeDescription: 'Read challenging sports terms smoothly!',
    reviewSkill1Id: 'prefixes_suffixes',
    reviewSkill2Id: 'phonics_decoding',
    sortOrder: 38,
  },
  {
    id: 'ela_3_rf_4_1',
    skillId: 'fluency_accuracy',
    name: 'Reading with Expression',
    displayName: 'Mystery Story Expression',
    description: 'Read with appropriate expression',
    theme: 'detective_mystery',
    themeDescription: 'Read mysteries with exciting expression!',
    reviewSkill1Id: 'multisyllable_words',
    reviewSkill2Id: 'prefixes_suffixes',
    sortOrder: 39,
  },
  {
    id: 'ela_3_rf_4_2',
    skillId: 'fluency_accuracy',
    name: 'Reading Fluently',
    displayName: 'Garden Story Flow',
    description: 'Read smoothly at an appropriate pace',
    theme: 'garden_explorer',
    themeDescription: 'Read garden stories with smooth flow!',
    reviewSkill1Id: 'multisyllable_words',
    reviewSkill2Id: 'prefixes_suffixes',
    sortOrder: 40,
  },

  // Writing (3.W)
  {
    id: 'ela_3_w_1_1',
    skillId: 'opinion_intro',
    name: 'Introducing Your Opinion',
    displayName: 'Pirate Debates',
    description: 'Write a clear opinion statement',
    theme: 'treasure_hunt',
    themeDescription: 'State your opinion in pirate debate style!',
    reviewSkill1Id: 'fluency_accuracy',
    reviewSkill2Id: 'multisyllable_words',
    sortOrder: 41,
  },
  {
    id: 'ela_3_w_1_2',
    skillId: 'opinion_intro',
    name: 'Organizing Opinion Writing',
    displayName: 'Space Mission Proposals',
    description: 'Create an organizational structure',
    theme: 'space_explorer',
    themeDescription: 'Organize proposals for space missions!',
    reviewSkill1Id: 'fluency_accuracy',
    reviewSkill2Id: 'multisyllable_words',
    sortOrder: 42,
  },
  {
    id: 'ela_3_w_2_1',
    skillId: 'opinion_reasons',
    name: 'Supporting Your Opinion',
    displayName: 'Animal Protection Arguments',
    description: 'Provide reasons for your opinion',
    theme: 'animal_kingdom',
    themeDescription: 'Give reasons why animals need protection!',
    reviewSkill1Id: 'opinion_intro',
    reviewSkill2Id: 'fluency_accuracy',
    sortOrder: 43,
  },
  {
    id: 'ela_3_w_2_2',
    skillId: 'opinion_reasons',
    name: 'Strong Reasons',
    displayName: 'Recipe Review Reasons',
    description: 'Choose the best reasons to support your opinion',
    theme: 'kitchen_chef',
    themeDescription: 'Write convincing recipe reviews!',
    reviewSkill1Id: 'opinion_intro',
    reviewSkill2Id: 'fluency_accuracy',
    sortOrder: 44,
  },
  {
    id: 'ela_3_w_3_1',
    skillId: 'opinion_linking',
    name: 'Linking Words in Opinions',
    displayName: 'Building Project Persuasion',
    description: 'Connect opinion and reasons with linking words',
    theme: 'builders_workshop',
    themeDescription: 'Connect your building ideas with linking words!',
    reviewSkill1Id: 'opinion_reasons',
    reviewSkill2Id: 'opinion_intro',
    sortOrder: 45,
  },
  {
    id: 'ela_3_w_3_2',
    skillId: 'opinion_linking',
    name: 'Concluding Opinions',
    displayName: 'Sports Editorial Conclusions',
    description: 'Write a strong conclusion for opinion pieces',
    theme: 'sports_champion',
    themeDescription: 'End your sports opinions with strong conclusions!',
    reviewSkill1Id: 'opinion_reasons',
    reviewSkill2Id: 'opinion_intro',
    sortOrder: 46,
  },
  {
    id: 'ela_3_w_4_1',
    skillId: 'informative_intro',
    name: 'Introducing Topics',
    displayName: 'Mystery Report Introductions',
    description: 'Write clear topic introductions',
    theme: 'detective_mystery',
    themeDescription: 'Introduce mystery investigation reports!',
    reviewSkill1Id: 'opinion_linking',
    reviewSkill2Id: 'opinion_reasons',
    sortOrder: 47,
  },
  {
    id: 'ela_3_w_4_2',
    skillId: 'informative_intro',
    name: 'Grouping Information',
    displayName: 'Garden Guide Organization',
    description: 'Group related information together',
    theme: 'garden_explorer',
    themeDescription: 'Organize gardening information clearly!',
    reviewSkill1Id: 'opinion_linking',
    reviewSkill2Id: 'opinion_reasons',
    sortOrder: 48,
  },
  {
    id: 'ela_3_w_5_1',
    skillId: 'informative_facts',
    name: 'Using Facts',
    displayName: 'Treasure Research Facts',
    description: 'Develop topics with facts and definitions',
    theme: 'treasure_hunt',
    themeDescription: 'Fill your treasure reports with amazing facts!',
    reviewSkill1Id: 'informative_intro',
    reviewSkill2Id: 'opinion_linking',
    sortOrder: 49,
  },
  {
    id: 'ela_3_w_5_2',
    skillId: 'informative_facts',
    name: 'Adding Details',
    displayName: 'Space Exploration Details',
    description: 'Include relevant details to inform readers',
    theme: 'space_explorer',
    themeDescription: 'Add fascinating details about space!',
    reviewSkill1Id: 'informative_intro',
    reviewSkill2Id: 'opinion_linking',
    sortOrder: 50,
  },
  {
    id: 'ela_3_w_6_1',
    skillId: 'informative_conclusion',
    name: 'Concluding Informative Writing',
    displayName: 'Animal Report Endings',
    description: 'Write effective conclusions',
    theme: 'animal_kingdom',
    themeDescription: 'End your animal reports memorably!',
    reviewSkill1Id: 'informative_facts',
    reviewSkill2Id: 'informative_intro',
    sortOrder: 51,
  },
  {
    id: 'ela_3_w_6_2',
    skillId: 'informative_conclusion',
    name: 'Wrapping Up',
    displayName: 'Recipe Article Conclusions',
    description: 'Provide satisfying ending statements',
    theme: 'kitchen_chef',
    themeDescription: 'Wrap up your food articles deliciously!',
    reviewSkill1Id: 'informative_facts',
    reviewSkill2Id: 'informative_intro',
    sortOrder: 52,
  },
  {
    id: 'ela_3_w_7_1',
    skillId: 'narrative_situation',
    name: 'Setting Up Stories',
    displayName: 'Builder Adventure Beginnings',
    description: 'Establish a situation and introduce characters',
    theme: 'builders_workshop',
    themeDescription: 'Start exciting building adventure stories!',
    reviewSkill1Id: 'informative_conclusion',
    reviewSkill2Id: 'informative_facts',
    sortOrder: 53,
  },
  {
    id: 'ela_3_w_7_2',
    skillId: 'narrative_situation',
    name: 'Character Introduction',
    displayName: 'Sports Hero Introductions',
    description: 'Introduce narrators and characters effectively',
    theme: 'sports_champion',
    themeDescription: 'Introduce your sports hero characters!',
    reviewSkill1Id: 'informative_conclusion',
    reviewSkill2Id: 'informative_facts',
    sortOrder: 54,
  },
  {
    id: 'ela_3_w_8_1',
    skillId: 'narrative_dialogue',
    name: 'Writing Dialogue',
    displayName: 'Detective Conversations',
    description: 'Use dialogue to develop characters',
    theme: 'detective_mystery',
    themeDescription: 'Write exciting detective conversations!',
    reviewSkill1Id: 'narrative_situation',
    reviewSkill2Id: 'informative_conclusion',
    sortOrder: 55,
  },
  {
    id: 'ela_3_w_8_2',
    skillId: 'narrative_dialogue',
    name: 'Describing Actions',
    displayName: 'Garden Story Descriptions',
    description: 'Use descriptions to develop events',
    theme: 'garden_explorer',
    themeDescription: 'Describe actions in garden adventures!',
    reviewSkill1Id: 'narrative_situation',
    reviewSkill2Id: 'informative_conclusion',
    sortOrder: 56,
  },
  {
    id: 'ela_3_w_9_1',
    skillId: 'narrative_sequence',
    name: 'Event Order',
    displayName: 'Pirate Journey Sequence',
    description: 'Use temporal words to show order',
    theme: 'treasure_hunt',
    themeDescription: 'Tell pirate journeys in the right order!',
    reviewSkill1Id: 'narrative_dialogue',
    reviewSkill2Id: 'narrative_situation',
    sortOrder: 57,
  },
  {
    id: 'ela_3_w_9_2',
    skillId: 'narrative_sequence',
    name: 'Transition Words',
    displayName: 'Space Mission Timeline',
    description: 'Use words like first, then, finally',
    theme: 'space_explorer',
    themeDescription: 'Sequence space mission events clearly!',
    reviewSkill1Id: 'narrative_dialogue',
    reviewSkill2Id: 'narrative_situation',
    sortOrder: 58,
  },
  {
    id: 'ela_3_w_10_1',
    skillId: 'writing_process',
    name: 'Planning Writing',
    displayName: 'Animal Story Planning',
    description: 'Plan before writing',
    theme: 'animal_kingdom',
    themeDescription: 'Plan your animal stories carefully!',
    reviewSkill1Id: 'narrative_sequence',
    reviewSkill2Id: 'narrative_dialogue',
    sortOrder: 59,
  },
  {
    id: 'ela_3_w_10_2',
    skillId: 'writing_process',
    name: 'Revising and Editing',
    displayName: 'Recipe Revision',
    description: 'Revise and edit your writing',
    theme: 'kitchen_chef',
    themeDescription: 'Perfect your recipe stories through revision!',
    reviewSkill1Id: 'narrative_sequence',
    reviewSkill2Id: 'narrative_dialogue',
    sortOrder: 60,
  },

  // Language (3.L) - Remaining lessons
  {
    id: 'ela_3_l_1_1',
    skillId: 'nouns_pronouns',
    name: 'Nouns in Sentences',
    displayName: 'Builder Noun Identification',
    description: 'Identify and use nouns correctly',
    theme: 'builders_workshop',
    themeDescription: 'Find all the nouns in building stories!',
    reviewSkill1Id: 'writing_process',
    reviewSkill2Id: 'narrative_sequence',
    sortOrder: 61,
  },
  {
    id: 'ela_3_l_1_2',
    skillId: 'nouns_pronouns',
    name: 'Pronouns',
    displayName: 'Sports Pronoun Practice',
    description: 'Use pronouns correctly',
    theme: 'sports_champion',
    themeDescription: 'Replace nouns with pronouns in sports writing!',
    reviewSkill1Id: 'writing_process',
    reviewSkill2Id: 'narrative_sequence',
    sortOrder: 62,
  },
  {
    id: 'ela_3_l_2_1',
    skillId: 'verbs_adjectives',
    name: 'Action Verbs',
    displayName: 'Detective Action Words',
    description: 'Identify and use action verbs',
    theme: 'detective_mystery',
    themeDescription: 'Find the action verbs in mystery stories!',
    reviewSkill1Id: 'nouns_pronouns',
    reviewSkill2Id: 'writing_process',
    sortOrder: 63,
  },
  {
    id: 'ela_3_l_2_2',
    skillId: 'verbs_adjectives',
    name: 'Adjectives',
    displayName: 'Garden Descriptive Words',
    description: 'Use adjectives to describe',
    theme: 'garden_explorer',
    themeDescription: 'Describe gardens with vivid adjectives!',
    reviewSkill1Id: 'nouns_pronouns',
    reviewSkill2Id: 'writing_process',
    sortOrder: 64,
  },
  {
    id: 'ela_3_l_3_1',
    skillId: 'adverbs',
    name: 'Using Adverbs',
    displayName: 'Pirate Adverb Adventures',
    description: 'Identify and use adverbs',
    theme: 'treasure_hunt',
    themeDescription: 'Describe how pirates act with adverbs!',
    reviewSkill1Id: 'verbs_adjectives',
    reviewSkill2Id: 'nouns_pronouns',
    sortOrder: 65,
  },
  {
    id: 'ela_3_l_3_2',
    skillId: 'adverbs',
    name: 'Adverbs in Writing',
    displayName: 'Space Travel Descriptions',
    description: 'Add adverbs to improve writing',
    theme: 'space_explorer',
    themeDescription: 'Describe space travel with adverbs!',
    reviewSkill1Id: 'verbs_adjectives',
    reviewSkill2Id: 'nouns_pronouns',
    sortOrder: 66,
  },
  {
    id: 'ela_3_l_4_1',
    skillId: 'plural_nouns_regular',
    name: 'Regular Plurals',
    displayName: 'Animal Plural Practice',
    description: 'Form regular plural nouns',
    theme: 'animal_kingdom',
    themeDescription: 'Practice plural animal names!',
    reviewSkill1Id: 'adverbs',
    reviewSkill2Id: 'verbs_adjectives',
    sortOrder: 67,
  },
  {
    id: 'ela_3_l_4_2',
    skillId: 'plural_nouns_regular',
    name: 'Plural Rules',
    displayName: 'Kitchen Items Plurals',
    description: 'Apply rules for forming plurals',
    theme: 'kitchen_chef',
    themeDescription: 'Make kitchen items plural correctly!',
    reviewSkill1Id: 'adverbs',
    reviewSkill2Id: 'verbs_adjectives',
    sortOrder: 68,
  },
  {
    id: 'ela_3_l_5_1',
    skillId: 'plural_nouns_irregular',
    name: 'Irregular Plurals',
    displayName: 'Builder Tools Plurals',
    description: 'Learn irregular plural forms',
    theme: 'builders_workshop',
    themeDescription: 'Master tricky plural tool names!',
    reviewSkill1Id: 'plural_nouns_regular',
    reviewSkill2Id: 'adverbs',
    sortOrder: 69,
  },
  {
    id: 'ela_3_l_5_2',
    skillId: 'plural_nouns_irregular',
    name: 'Unusual Plurals',
    displayName: 'Sports Equipment Plurals',
    description: 'Practice unusual plural forms',
    theme: 'sports_champion',
    themeDescription: 'Learn the plural forms of sports gear!',
    reviewSkill1Id: 'plural_nouns_regular',
    reviewSkill2Id: 'adverbs',
    sortOrder: 70,
  },
  {
    id: 'ela_3_l_6_1',
    skillId: 'abstract_nouns',
    name: 'Abstract Nouns',
    displayName: 'Mystery Feelings',
    description: 'Understand and use abstract nouns',
    theme: 'detective_mystery',
    themeDescription: 'Express feelings and ideas in mysteries!',
    reviewSkill1Id: 'plural_nouns_irregular',
    reviewSkill2Id: 'plural_nouns_regular',
    sortOrder: 71,
  },
  {
    id: 'ela_3_l_6_2',
    skillId: 'abstract_nouns',
    name: 'Ideas and Feelings',
    displayName: 'Garden Emotions',
    description: 'Use abstract nouns in writing',
    theme: 'garden_explorer',
    themeDescription: 'Write about garden feelings and ideas!',
    reviewSkill1Id: 'plural_nouns_irregular',
    reviewSkill2Id: 'plural_nouns_regular',
    sortOrder: 72,
  },
  {
    id: 'ela_3_l_7_1',
    skillId: 'verb_tenses',
    name: 'Past Tense Verbs',
    displayName: 'Pirate History Tenses',
    description: 'Form and use past tense verbs',
    theme: 'treasure_hunt',
    themeDescription: 'Tell pirate history using past tense!',
    reviewSkill1Id: 'abstract_nouns',
    reviewSkill2Id: 'plural_nouns_irregular',
    sortOrder: 73,
  },
  {
    id: 'ela_3_l_7_2',
    skillId: 'verb_tenses',
    name: 'Future Tense Verbs',
    displayName: 'Space Future Plans',
    description: 'Form and use future tense verbs',
    theme: 'space_explorer',
    themeDescription: 'Plan space missions using future tense!',
    reviewSkill1Id: 'abstract_nouns',
    reviewSkill2Id: 'plural_nouns_irregular',
    sortOrder: 74,
  },
  {
    id: 'ela_3_l_8_1',
    skillId: 'subject_verb_agreement',
    name: 'Subject-Verb Agreement',
    displayName: 'Animal Grammar Match',
    description: 'Make subjects and verbs agree',
    theme: 'animal_kingdom',
    themeDescription: 'Match subjects and verbs in animal sentences!',
    reviewSkill1Id: 'verb_tenses',
    reviewSkill2Id: 'abstract_nouns',
    sortOrder: 75,
  },
  {
    id: 'ela_3_l_8_2',
    skillId: 'subject_verb_agreement',
    name: 'Pronoun Agreement',
    displayName: 'Recipe Pronoun Matching',
    description: 'Ensure pronouns agree with antecedents',
    theme: 'kitchen_chef',
    themeDescription: 'Match pronouns correctly in recipes!',
    reviewSkill1Id: 'verb_tenses',
    reviewSkill2Id: 'abstract_nouns',
    sortOrder: 76,
  },
  {
    id: 'ela_3_l_9_1',
    skillId: 'comparative_superlative',
    name: 'Comparing with Adjectives',
    displayName: 'Building Comparisons',
    description: 'Use comparative adjectives',
    theme: 'builders_workshop',
    themeDescription: 'Compare buildings using adjectives!',
    reviewSkill1Id: 'subject_verb_agreement',
    reviewSkill2Id: 'verb_tenses',
    sortOrder: 77,
  },
  {
    id: 'ela_3_l_9_2',
    skillId: 'comparative_superlative',
    name: 'Superlative Forms',
    displayName: 'Sports Record Superlatives',
    description: 'Use superlative adjectives and adverbs',
    theme: 'sports_champion',
    themeDescription: 'Describe sports records with superlatives!',
    reviewSkill1Id: 'subject_verb_agreement',
    reviewSkill2Id: 'verb_tenses',
    sortOrder: 78,
  },
  {
    id: 'ela_3_l_10_1',
    skillId: 'conjunctions',
    name: 'Coordinating Conjunctions',
    displayName: 'Detective Connecting Words',
    description: 'Use and, but, or, so',
    theme: 'detective_mystery',
    themeDescription: 'Connect clues with conjunctions!',
    reviewSkill1Id: 'comparative_superlative',
    reviewSkill2Id: 'subject_verb_agreement',
    sortOrder: 79,
  },
  {
    id: 'ela_3_l_10_2',
    skillId: 'conjunctions',
    name: 'Subordinating Conjunctions',
    displayName: 'Garden Cause and Effect',
    description: 'Use because, when, if, although',
    theme: 'garden_explorer',
    themeDescription: 'Explain garden cause and effect with conjunctions!',
    reviewSkill1Id: 'comparative_superlative',
    reviewSkill2Id: 'subject_verb_agreement',
    sortOrder: 80,
  },
  {
    id: 'ela_3_l_11_1',
    skillId: 'simple_compound_sentences',
    name: 'Simple Sentences',
    displayName: 'Pirate Simple Statements',
    description: 'Write clear simple sentences',
    theme: 'treasure_hunt',
    themeDescription: 'Write clear pirate statements!',
    reviewSkill1Id: 'conjunctions',
    reviewSkill2Id: 'comparative_superlative',
    sortOrder: 81,
  },
  {
    id: 'ela_3_l_11_2',
    skillId: 'simple_compound_sentences',
    name: 'Compound Sentences',
    displayName: 'Space Compound Ideas',
    description: 'Combine ideas into compound sentences',
    theme: 'space_explorer',
    themeDescription: 'Combine space ideas into longer sentences!',
    reviewSkill1Id: 'conjunctions',
    reviewSkill2Id: 'comparative_superlative',
    sortOrder: 82,
  },
  {
    id: 'ela_3_l_12_1',
    skillId: 'capitalization',
    name: 'Title Capitalization',
    displayName: 'Animal Book Titles',
    description: 'Capitalize words in titles correctly',
    theme: 'animal_kingdom',
    themeDescription: 'Capitalize animal book titles correctly!',
    reviewSkill1Id: 'simple_compound_sentences',
    reviewSkill2Id: 'conjunctions',
    sortOrder: 83,
  },
  {
    id: 'ela_3_l_12_2',
    skillId: 'capitalization',
    name: 'Proper Capitalization',
    displayName: 'Recipe Name Capitals',
    description: 'Apply capitalization rules',
    theme: 'kitchen_chef',
    themeDescription: 'Capitalize recipe names properly!',
    reviewSkill1Id: 'simple_compound_sentences',
    reviewSkill2Id: 'conjunctions',
    sortOrder: 84,
  },
  {
    id: 'ela_3_l_13_1',
    skillId: 'commas_addresses',
    name: 'Commas in Addresses',
    displayName: 'Builder Location Writing',
    description: 'Use commas correctly in addresses',
    theme: 'builders_workshop',
    themeDescription: 'Write building addresses with correct commas!',
    reviewSkill1Id: 'capitalization',
    reviewSkill2Id: 'simple_compound_sentences',
    sortOrder: 85,
  },
  {
    id: 'ela_3_l_13_2',
    skillId: 'commas_addresses',
    name: 'City and State Commas',
    displayName: 'Sports Venue Addresses',
    description: 'Place commas between city and state',
    theme: 'sports_champion',
    themeDescription: 'Write stadium addresses correctly!',
    reviewSkill1Id: 'capitalization',
    reviewSkill2Id: 'simple_compound_sentences',
    sortOrder: 86,
  },
  {
    id: 'ela_3_l_14_1',
    skillId: 'commas_dialogue',
    name: 'Dialogue Punctuation',
    displayName: 'Detective Dialogue Writing',
    description: 'Use commas in dialogue',
    theme: 'detective_mystery',
    themeDescription: 'Punctuate detective conversations correctly!',
    reviewSkill1Id: 'commas_addresses',
    reviewSkill2Id: 'capitalization',
    sortOrder: 87,
  },
  {
    id: 'ela_3_l_14_2',
    skillId: 'commas_dialogue',
    name: 'Quotation Marks',
    displayName: 'Garden Story Quotes',
    description: 'Use quotation marks with dialogue',
    theme: 'garden_explorer',
    themeDescription: 'Add quotation marks to garden story dialogue!',
    reviewSkill1Id: 'commas_addresses',
    reviewSkill2Id: 'capitalization',
    sortOrder: 88,
  },
];

// ============================================================================
// COMBINED EXPORTS
// ============================================================================

export const allGrade3Lessons: Lesson[] = [...grade3MathLessons, ...grade3ELALessons];

export function getLessonById(id: string): Lesson | undefined {
  return allGrade3Lessons.find(l => l.id === id);
}

export function getLessonsBySkill(skillId: string): Lesson[] {
  return allGrade3Lessons.filter(l => l.skillId === skillId);
}

export function getLessonsByTheme(theme: ThemeCode): Lesson[] {
  return allGrade3Lessons.filter(l => l.theme === theme);
}
